POST http://localhost:8080/signup

{
  "rollno": 190197,
  "name": "Asish Kumar Mandoi",
  "password": "sTr0nGp@$5w0rD"
}

###
GET http://localhost:8080/login

###
POST http://localhost:8080/login

{
  "rollno": 190197,
  "password": "sTr0nGp@$5w0rD"
}

###
POST http://localhost:8080/secretpage

###
GET http://localhost:8080/secretpage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjMyNDI1NjAsInJvbGxubyI6MTkwMTk3fQ.VebSa6pNUZuHN4GKLahvARU27ILGsWuATjbmW30mnJY